services:
  flask-api:
    build: .
    container_name: portfolio-project-2-api
    ports:
      - "5000:5000"

  prometheus:
    image: prom/prometheus:latest
    container_name: portfolio-project-2-prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./prometheus/alerts.yml:/etc/prometheus/alerts.yml

  grafana:
    image: grafana/grafana:latest
    container_name: portfolio-project-2-grafana
    ports:
      - "3000:3000"
    environment:
      GF_SECURITY_ADMIN_USER: ${GRAFANA_ADMIN_USER}
      GF_SECURITY_ADMIN_PASSWORD: ${GRAFANA_ADMIN_PASSWORD}
    volumes:
      - grafana-storage:/var/lib/grafana

  node-exporter:
    image: prom/node-exporter:latest
    container_name: portfolio-project-2-node-exporter
    ports:
      - "9100:9100"

volumes:
  grafana-storage: